# Generated by Django 5.0.3 on 2024-05-11 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0005_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hobby',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='hobbies',
            new_name='titles',
        ),
    ]
