# Generated by Django 5.0.3 on 2024-05-11 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0006_rename_hobby_title_rename_hobbies_student_titles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title',
            new_name='Hobby',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='titles',
            new_name='hobbies',
        ),
    ]
